export type GameMode = 'zhuyin' | 'english'

export interface VoicePrompt {
  id: string
  displayPrimary: string
  displaySecondary: string
  hint?: string
  stage1: string[]
  stage2: string[]
  timeMs: number
  damage: number
}

/** Sourced from design/voice-prompts-v1.json (+4s STT buffer on timeMs) */
const ZHUYIN_PROMPTS: VoicePrompt[] = [
  {
    id: "z_b",
    displayPrimary: "ㄅ",
    displaySecondary: "八",
    hint: "b / bo",
    stage1: ["ㄅ", "b", "bo", "ba", "八"],
    stage2: ["八"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_p",
    displayPrimary: "ㄆ",
    displaySecondary: "皮",
    hint: "p / po",
    stage1: ["ㄆ", "p", "po", "pi", "皮"],
    stage2: ["皮"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_m",
    displayPrimary: "ㄇ",
    displaySecondary: "媽",
    hint: "m / mo",
    stage1: ["ㄇ", "m", "mo", "ma", "媽"],
    stage2: ["媽"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_f",
    displayPrimary: "ㄈ",
    displaySecondary: "飛",
    hint: "f / fo",
    stage1: ["ㄈ", "f", "fo", "fei", "飛"],
    stage2: ["飛"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_d",
    displayPrimary: "ㄉ",
    displaySecondary: "大",
    hint: "d / de",
    stage1: ["ㄉ", "d", "de", "da", "大"],
    stage2: ["大"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_t",
    displayPrimary: "ㄊ",
    displaySecondary: "他",
    hint: "t / te",
    stage1: ["ㄊ", "t", "te", "ta", "他"],
    stage2: ["他"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_n",
    displayPrimary: "ㄋ",
    displaySecondary: "你",
    hint: "n / ne",
    stage1: ["ㄋ", "n", "ne", "ni", "你"],
    stage2: ["你"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_l",
    displayPrimary: "ㄌ",
    displaySecondary: "了",
    hint: "l / le",
    stage1: ["ㄌ", "l", "le", "liao", "了"],
    stage2: ["了"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_g",
    displayPrimary: "ㄍ",
    displaySecondary: "哥",
    hint: "g / ge",
    stage1: ["ㄍ", "g", "ge", "哥"],
    stage2: ["哥"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_k",
    displayPrimary: "ㄎ",
    displaySecondary: "可",
    hint: "k / ke",
    stage1: ["ㄎ", "k", "ke", "可"],
    stage2: ["可"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_h",
    displayPrimary: "ㄏ",
    displaySecondary: "喝",
    hint: "h / he",
    stage1: ["ㄏ", "h", "he", "喝"],
    stage2: ["喝"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_j",
    displayPrimary: "ㄐ",
    displaySecondary: "雞",
    hint: "j / ji",
    stage1: ["ㄐ", "j", "ji", "雞", "鸡"],
    stage2: ["雞", "鸡"],
    timeMs: 10000,
    damage: 18,
  },
  {
    id: "z_q",
    displayPrimary: "ㄑ",
    displaySecondary: "七",
    hint: "q / qi",
    stage1: ["ㄑ", "q", "qi", "七"],
    stage2: ["七"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_x",
    displayPrimary: "ㄒ",
    displaySecondary: "西",
    hint: "x / xi",
    stage1: ["ㄒ", "x", "xi", "西"],
    stage2: ["西"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_zh",
    displayPrimary: "ㄓ",
    displaySecondary: "知",
    hint: "zh / zhi",
    stage1: ["ㄓ", "zh", "zhi", "知"],
    stage2: ["知"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_ch",
    displayPrimary: "ㄔ",
    displaySecondary: "吃",
    hint: "ch / chi",
    stage1: ["ㄔ", "ch", "chi", "吃"],
    stage2: ["吃"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_sh",
    displayPrimary: "ㄕ",
    displaySecondary: "是",
    hint: "sh / shi",
    stage1: ["ㄕ", "sh", "shi", "是"],
    stage2: ["是"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_r",
    displayPrimary: "ㄖ",
    displaySecondary: "日",
    hint: "r / ri",
    stage1: ["ㄖ", "r", "ri", "日"],
    stage2: ["日"],
    timeMs: 10000,
    damage: 16,
  },
  {
    id: "z_zhao",
    displayPrimary: "ㄓㄠ",
    displaySecondary: "罩",
    hint: "zhao",
    stage1: ["ㄓㄠˋ", "ㄓㄠ", "zhao4", "zhao", "ㄓㄠ4", "罩"],
    stage2: ["罩"],
    timeMs: 10500,
    damage: 18,
  },
  {
    id: "z_huo",
    displayPrimary: "ㄏㄨㄛ",
    displaySecondary: "火",
    hint: "huo",
    stage1: ["ㄏㄨㄛˇ", "ㄏㄨㄛ", "huo3", "huo", "火"],
    stage2: ["火"],
    timeMs: 10500,
    damage: 18,
  },
  {
    id: "z_jian",
    displayPrimary: "ㄐㄧㄢ",
    displaySecondary: "劍",
    hint: "jian",
    stage1: ["ㄐㄧㄢˋ", "ㄐㄧㄢ", "jian4", "jian", "劍"],
    stage2: ["劍"],
    timeMs: 11000,
    damage: 20,
  },
  {
    id: "z_shui",
    displayPrimary: "ㄕㄨㄟ",
    displaySecondary: "水",
    hint: "shui",
    stage1: ["ㄕㄨㄟˇ", "ㄕㄨㄟ", "shui3", "shui", "水"],
    stage2: ["水"],
    timeMs: 10500,
    damage: 18,
  },
]
const ENGLISH_PROMPTS: VoicePrompt[] = [
  {
    id: "e_apple",
    displayPrimary: "A-P-P-L-E",
    displaySecondary: "APPLE",
    stage1: ["A P P L E","APPLE","ay pee pee el ee"],
    stage2: ["APPLE","apple"],
    timeMs: 12000,
    damage: 22,
  },
  {
    id: "e_hit",
    displayPrimary: "H-I-T",
    displaySecondary: "HIT",
    stage1: ["H I T","HIT"],
    stage2: ["HIT","hit"],
    timeMs: 9500,
    damage: 14,
  },
  {
    id: "e_fire",
    displayPrimary: "F-I-R-E",
    displaySecondary: "FIRE",
    stage1: ["F I R E","FIRE"],
    stage2: ["FIRE","fire"],
    timeMs: 10500,
    damage: 16,
  },
  {
    id: "e_slash",
    displayPrimary: "S-L-A-S-H",
    displaySecondary: "SLASH",
    stage1: ["S L A S H","SLASH"],
    stage2: ["SLASH","slash"],
    timeMs: 11500,
    damage: 18,
  },
  {
    id: "e_hero",
    displayPrimary: "H-E-R-O",
    displaySecondary: "HERO",
    stage1: ["H E R O","HERO"],
    stage2: ["HERO","hero"],
    timeMs: 10500,
    damage: 16,
  },
  {
    id: "e_sword",
    displayPrimary: "S-W-O-R-D",
    displaySecondary: "SWORD",
    stage1: ["S W O R D","SWORD"],
    stage2: ["SWORD","sword"],
    timeMs: 11500,
    damage: 18,
  },
  {
    id: "e_magic",
    displayPrimary: "M-A-G-I-C",
    displaySecondary: "MAGIC",
    stage1: ["M A G I C","MAGIC"],
    stage2: ["MAGIC","magic"],
    timeMs: 11500,
    damage: 18,
  },
  {
    id: "e_attack",
    displayPrimary: "A-T-T-A-C-K",
    displaySecondary: "ATTACK",
    stage1: ["A T T A C K","ATTACK"],
    stage2: ["ATTACK","attack"],
    timeMs: 12000,
    damage: 22,
  },
  {
    id: "e_combo",
    displayPrimary: "C-O-M-B-O",
    displaySecondary: "COMBO",
    stage1: ["C O M B O","COMBO"],
    stage2: ["COMBO","combo"],
    timeMs: 11000,
    damage: 18,
  },
  {
    id: "e_power",
    displayPrimary: "P-O-W-E-R",
    displaySecondary: "POWER",
    stage1: ["P O W E R","POWER"],
    stage2: ["POWER","power"],
    timeMs: 11000,
    damage: 18,
  },
  {
    id: "e_fast",
    displayPrimary: "F-A-S-T",
    displaySecondary: "FAST",
    stage1: ["F A S T","FAST"],
    stage2: ["FAST","fast"],
    timeMs: 10000,
    damage: 15,
  },
  {
    id: "e_win",
    displayPrimary: "W-I-N",
    displaySecondary: "WIN",
    stage1: ["W I N","WIN"],
    stage2: ["WIN","win"],
    timeMs: 9500,
    damage: 14,
  },
  {
    id: "e_guard",
    displayPrimary: "G-U-A-R-D",
    displaySecondary: "GUARD",
    stage1: ["G U A R D","GUARD"],
    stage2: ["GUARD","guard"],
    timeMs: 11000,
    damage: 18,
  },
  {
    id: "e_smash",
    displayPrimary: "S-M-A-S-H",
    displaySecondary: "SMASH",
    stage1: ["S M A S H","SMASH"],
    stage2: ["SMASH","smash"],
    timeMs: 11000,
    damage: 18,
  },
  {
    id: "e_brave",
    displayPrimary: "B-R-A-V-E",
    displaySecondary: "BRAVE",
    stage1: ["B R A V E","BRAVE"],
    stage2: ["BRAVE","brave"],
    timeMs: 11500,
    damage: 20,
  },
  {
    id: "e_fight",
    displayPrimary: "F-I-G-H-T",
    displaySecondary: "FIGHT",
    stage1: ["F I G H T","FIGHT"],
    stage2: ["FIGHT","fight"],
    timeMs: 11000,
    damage: 18,
  },
]

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export function createPromptDeck(mode: GameMode): VoicePrompt[] {
  return shuffle(mode === 'zhuyin' ? ZHUYIN_PROMPTS : ENGLISH_PROMPTS)
}

export function speechLang(mode: GameMode): string {
  return mode === 'zhuyin' ? 'zh-TW' : 'en-US'
}
